; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Apr 27 2018 18:04:17 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATACYMPJGUOH4H:
	dc.w $0, DATACYMPJGUOH4H_1-DATACYMPJGUOH4H
	dc.w DATACYMPJGUOH4H_2-DATACYMPJGUOH4H, $0
	dc.w DATACYMPJGUOH4H_4-DATACYMPJGUOH4H, DATACYMPJGUOH4H_5-DATACYMPJGUOH4H
	dc.w DATACYMPJGUOH4H_6-DATACYMPJGUOH4H, DATACYMPJGUOH4H_7-DATACYMPJGUOH4H
DATACYMPJGUOH4H_1: dc.b $6
	dc.b $0, $C, $0, $E7, $1C
	dc.b $0, $0, $0, $EA, $3C
	dc.b $0, $0, $0, $EA, $4C
	dc.b $0, $0, $0, $EB, $54
	dc.b $0, $4, $0, $EC, $5C
	dc.b $0, $0, $0, $EB, $6C
DATACYMPJGUOH4H_2: dc.b $1E
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $B8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $D8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
	dc.b $F8, $F, $0, $0, $80
DATACYMPJGUOH4H_4: dc.b $5
	dc.b $0, $0, $0, $EA, $35
	dc.b $0, $4, $0, $F0, $3D
	dc.b $0, $0, $0, $F2, $4B
	dc.b $0, $0, $0, $F3, $52
	dc.b $0, $0, $8, $EE, $62
DATACYMPJGUOH4H_5: dc.b $8
	dc.b $0, $0, $0, $EA, $31
	dc.b $0, $0, $0, $F4, $39
	dc.b $0, $0, $0, $EC, $41
	dc.b $0, $0, $0, $F5, $49
	dc.b $0, $0, $0, $F0, $51
	dc.b $0, $0, $0, $F6, $59
	dc.b $0, $0, $0, $EE, $28
	dc.b $0, $0, $8, $EE, $62
DATACYMPJGUOH4H_6: dc.b $6
	dc.b $0, $0, $0, $F7, $35
	dc.b $0, $0, $0, $E9, $3D
	dc.b $0, $4, $0, $EB, $45
	dc.b $0, $0, $0, $F8, $55
	dc.b $0, $0, $0, $EE, $28
	dc.b $0, $0, $8, $EE, $62
DATACYMPJGUOH4H_7: dc.b $7
	dc.b $0, $0, $0, $F7, $33
	dc.b $0, $0, $0, $EE, $28
	dc.b $0, $0, $0, $F2, $39
	dc.b $0, $0, $0, $F9, $40
	dc.b $0, $0, $0, $F4, $48
	dc.b $0, $0, $0, $EB, $50
	dc.b $0, $0, $0, $FA, $58
	even