; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Apr 22 2018 00:45:43 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAH2GM7QB991V:
	dc.w DATAH2GM7QB991V_0-DATAH2GM7QB991V, DATAH2GM7QB991V_1-DATAH2GM7QB991V
	dc.w DATAH2GM7QB991V_2-DATAH2GM7QB991V, DATAH2GM7QB991V_3-DATAH2GM7QB991V
	dc.w DATAH2GM7QB991V_4-DATAH2GM7QB991V, DATAH2GM7QB991V_5-DATAH2GM7QB991V
	dc.w DATAH2GM7QB991V_6-DATAH2GM7QB991V, DATAH2GM7QB991V_7-DATAH2GM7QB991V
	dc.w DATAH2GM7QB991V_8-DATAH2GM7QB991V, DATAH2GM7QB991V_9-DATAH2GM7QB991V
	dc.w DATAH2GM7QB991V_A-DATAH2GM7QB991V, DATAH2GM7QB991V_B-DATAH2GM7QB991V
DATAH2GM7QB991V_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_2: dc.b $2
	dc.b $F2, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_3: dc.b $2
	dc.b $F2, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_4: dc.b $2
	dc.b $F2, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_5: dc.b $2
	dc.b $F2, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_6: dc.b $2
	dc.b $F2, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_7: dc.b $2
	dc.b $F2, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_8: dc.b $2
	dc.b $F2, $5, $20, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_9: dc.b $2
	dc.b $F2, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_A: dc.b $2
	dc.b $F2, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAH2GM7QB991V_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even