; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 31 2018 18:31:04 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAY17EXS3PFEL:
	dc.w $0, DATAY17EXS3PFEL_1-DATAY17EXS3PFEL
	dc.w DATAY17EXS3PFEL_2-DATAY17EXS3PFEL, DATAY17EXS3PFEL_3-DATAY17EXS3PFEL
	dc.w DATAY17EXS3PFEL_4-DATAY17EXS3PFEL, DATAY17EXS3PFEL_5-DATAY17EXS3PFEL
	dc.w DATAY17EXS3PFEL_6-DATAY17EXS3PFEL, DATAY17EXS3PFEL_7-DATAY17EXS3PFEL
	dc.w DATAY17EXS3PFEL_8-DATAY17EXS3PFEL, DATAY17EXS3PFEL_9-DATAY17EXS3PFEL
	dc.w DATAY17EXS3PFEL_A-DATAY17EXS3PFEL
DATAY17EXS3PFEL_1: dc.b $4
	dc.b $F0, $5, $0, $0, $0
	dc.b $0, $5, $10, $0, $0
	dc.b $F0, $5, $8, $0, $F0
	dc.b $0, $5, $18, $0, $F0
DATAY17EXS3PFEL_2: dc.b $4
	dc.b $F0, $5, $0, $4, $F0
	dc.b $0, $5, $10, $4, $F0
	dc.b $F0, $5, $8, $4, $0
	dc.b $0, $5, $18, $4, $0
DATAY17EXS3PFEL_3: dc.b $4
	dc.b $F0, $5, $8, $8, $F0
	dc.b $0, $5, $18, $8, $F0
	dc.b $0, $5, $10, $8, $0
	dc.b $F0, $5, $0, $8, $0
DATAY17EXS3PFEL_4: dc.b $4
	dc.b $F0, $5, $0, $C, $F0
	dc.b $0, $5, $10, $C, $F0
	dc.b $0, $5, $18, $C, $0
	dc.b $F0, $5, $8, $C, $0
DATAY17EXS3PFEL_5: dc.b $4
	dc.b $F0, $5, $0, $10, $F0
	dc.b $0, $5, $10, $10, $F0
	dc.b $0, $5, $18, $10, $0
	dc.b $F0, $5, $8, $10, $0
DATAY17EXS3PFEL_6: dc.b $10
	dc.b $E8, $6, $0, $14, $E8
	dc.b $E8, $0, $0, $1A, $F8
	dc.b $EA, $0, $0, $18, $F7
	dc.b $E9, $0, $10, $19, $FA
	dc.b $E8, $6, $8, $14, $8
	dc.b $E8, $0, $8, $1A, $0
	dc.b $EA, $0, $8, $18, $1
	dc.b $E9, $0, $10, $19, $4
	dc.b $0, $6, $10, $14, $E8
	dc.b $10, $0, $10, $1A, $F8
	dc.b $0, $6, $18, $14, $8
	dc.b $10, $0, $18, $1A, $0
	dc.b $E, $0, $10, $18, $F7
	dc.b $F, $0, $0, $19, $FA
	dc.b $E, $0, $18, $18, $1
	dc.b $F, $0, $8, $19, $FE
DATAY17EXS3PFEL_7: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $E8, $A, $0, $9, $0
	dc.b $0, $A, $18, $9, $E8
	dc.b $0, $A, $18, $0, $0
DATAY17EXS3PFEL_8: dc.b $4
	dc.b $E8, $A, $8, $9, $E8
	dc.b $E8, $A, $8, $0, $0
	dc.b $0, $A, $10, $0, $E8
	dc.b $0, $A, $10, $9, $0
DATAY17EXS3PFEL_9: dc.b $4
	dc.b $E8, $A, $0, $12, $E8
	dc.b $E8, $A, $0, $1B, $0
	dc.b $0, $A, $18, $1B, $E8
	dc.b $0, $A, $18, $12, $0
DATAY17EXS3PFEL_A: dc.b $4
	dc.b $E8, $A, $8, $1B, $E8
	dc.b $E8, $A, $8, $12, $0
	dc.b $0, $A, $10, $12, $E8
	dc.b $0, $A, $10, $1B, $0
	even